#!/usr/bin/env node

// ============================================================================
// Follow Builders — Save Structured Digest
// ============================================================================
// Reads a structured digest JSON from stdin, then:
//   1. Merges it into digest-data.js in the repo root (multi-day, keyed by date)
//   2. Archives a timestamped copy to ~/.follow-builders/digests/
//
// Usage:
//   echo '<structured JSON>' | node save-digest.js
//
// The structured JSON must have the shape:
//   { date, generatedAt, language, builders: [...], podcasts: [...] }
//
// digest-data.js sets window.DIGEST_DATA so digest.html can load it
// directly via <script src>, even when opened as a local file://.
//
// Data retention: entries older than 30 days are automatically pruned.
// ============================================================================

import { readFile, writeFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const SCRIPT_DIR = decodeURIComponent(new URL('.', import.meta.url).pathname);
const REPO_ROOT  = join(SCRIPT_DIR, '..');
const DATA_PATH  = join(REPO_ROOT, 'digest-data.js');
const USER_DIR   = join(homedir(), '.follow-builders', 'digests');
const RETAIN_DAYS = 30;

async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString('utf-8');
}

async function loadExisting() {
  if (!existsSync(DATA_PATH)) return {};
  try {
    const src = await readFile(DATA_PATH, 'utf-8');
    const match = src.match(/window\.DIGEST_DATA\s*=\s*(\{[\s\S]+\});/);
    if (!match) return {};
    const parsed = JSON.parse(match[1]);
    // Migrate from old single-day format { date, builders, podcasts, ... }
    // to new multi-day format { "YYYY-MM-DD": { ... }, ... }
    if (parsed.date && parsed.builders) {
      return { [parsed.date]: parsed };
    }
    return parsed;
  } catch {
    return {};
  }
}

async function main() {
  const raw = await readStdin();

  let data;
  try {
    data = JSON.parse(raw.trim());
  } catch {
    console.error(JSON.stringify({ status: 'error', message: 'Invalid JSON on stdin' }));
    process.exit(1);
  }

  // Validate required fields
  const missing = ['date', 'builders', 'podcasts'].filter(k => !(k in data));
  if (missing.length > 0) {
    console.error(JSON.stringify({
      status: 'error',
      message: `Missing required fields: ${missing.join(', ')}`
    }));
    process.exit(1);
  }

  // Load existing multi-day store
  const allDigests = await loadExisting();

  // Insert/overwrite today's entry
  allDigests[data.date] = data;

  // Prune entries older than RETAIN_DAYS
  const cutoff = new Date(Date.now() - RETAIN_DAYS * 86_400_000)
    .toISOString().slice(0, 10);
  for (const key of Object.keys(allDigests)) {
    if (key < cutoff) delete allDigests[key];
  }

  // Write digest-data.js
  const jsContent =
    `// Auto-generated by save-digest.js — do not edit manually\n` +
    `window.DIGEST_DATA = ${JSON.stringify(allDigests, null, 2)};\n`;
  await writeFile(DATA_PATH, jsContent, 'utf-8');

  // Archive to ~/.follow-builders/digests/<date>.json
  await mkdir(USER_DIR, { recursive: true });
  await writeFile(
    join(USER_DIR, `${data.date}.json`),
    JSON.stringify(data, null, 2),
    'utf-8'
  );

  const dates = Object.keys(allDigests).sort().reverse();
  console.log(JSON.stringify({
    status: 'ok',
    message: `Digest saved. Open digest.html in your browser to view it.`,
    date: data.date,
    builders: data.builders.length,
    podcasts: data.podcasts.length,
    blogs: (data.blogs || []).length,
    storedDates: dates,
  }));
}

main().catch(err => {
  console.error(JSON.stringify({ status: 'error', message: err.message }));
  process.exit(1);
});
